# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceType: ClusterIP
ServiceAnnotations:
  getambassador.io/config: |
    ---
    apiVersion: ambassador/v0
    kind:  Mapping
    name:  croc-hunter_mapping
    prefix: /
    service: croc-hunter-croc-hunter.croc-hunter:80
    host: croc-hunter.dev.activedisclosure.com
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 3
image: "dfsacr.azurecr.io/dfsacr/croc-hunter"
imageTag: "latest"
imagePullPolicy: "Always"
cpu: "10m"
memory: "128Mi"
nodeSelector:
  beta.kubernetes.io/os: linux
# Ingress settings
ingress:
  enabled: false
  # hostname: croc-hunter.ddns.net
  annotations:
     # kubernetes.io/ingress.class: nginx
     # kubernetes.io/tls-acme: "true"
  tls: false
# PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2

rbac:
  install: true
  serviceAccountName: default
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
